#!/usr/bin/env bash
# Script that manages PID file and multiple signals

# Write PID to file
echo "$$" > /tmp/myscript.pid

# Trap SIGINT to display specific message
trap "echo 'Y U no love me?!'" SIGINT

# Trap SIGTERM and SIGQUIT to clean up and exit
trap "echo 'I hate the kill command'; rm /tmp/myscript.pid; exit" SIGTERM SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2 &
    wait $!
done
