#!/usr/bin/env bash
# Script that manages PID file and multiple signals
echo "$$" > /tmp/myscript.pid

trap "echo I hate the kill command; rm /tmp/myscript.pid; exit" SIGTERM SIGQUIT
trap "echo Y u no love me?!" SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 2 &
    wait $!
done
